/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

/**
 *
 * @author andre
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        visor = new javax.swing.JTextField();
        c_btn = new javax.swing.JButton();
        v_btn = new javax.swing.JButton();
        div_btn = new javax.swing.JButton();
        mult_btn = new javax.swing.JButton();
        menos_btn = new javax.swing.JButton();
        mais_btn = new javax.swing.JButton();
        igual_btn = new javax.swing.JButton();
        ponto_btn = new javax.swing.JButton();
        zero_btn = new javax.swing.JButton();
        um_btn = new javax.swing.JButton();
        quatro_btn = new javax.swing.JButton();
        sete_btn = new javax.swing.JButton();
        oito_btn = new javax.swing.JButton();
        nove_btn = new javax.swing.JButton();
        seis_btn = new javax.swing.JButton();
        cinco_btn = new javax.swing.JButton();
        dois_btn = new javax.swing.JButton();
        tres_btn = new javax.swing.JButton();
        ce_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaptionBorder);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        visor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        visor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        visor.setBorder(null);
        visor.setOpaque(false);

        c_btn.setBackground(new java.awt.Color(106, 52, 52));
        c_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c_btn.setText("C");

        v_btn.setBackground(new java.awt.Color(106, 52, 52));
        v_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        v_btn.setText("<");

        div_btn.setBackground(new java.awt.Color(126, 134, 145));
        div_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        div_btn.setText("/");

        mult_btn.setBackground(new java.awt.Color(126, 134, 145));
        mult_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mult_btn.setText("X");

        menos_btn.setBackground(new java.awt.Color(126, 134, 145));
        menos_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menos_btn.setText("-");

        mais_btn.setBackground(new java.awt.Color(126, 134, 145));
        mais_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mais_btn.setText("+");

        igual_btn.setBackground(java.awt.SystemColor.activeCaption);
        igual_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        igual_btn.setText("=");

        ponto_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ponto_btn.setText(".");

        zero_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zero_btn.setText("0");
        zero_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_btnActionPerformed(evt);
            }
        });

        um_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        um_btn.setText("1");
        um_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                um_btnActionPerformed(evt);
            }
        });

        quatro_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quatro_btn.setText("4");
        quatro_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatro_btnActionPerformed(evt);
            }
        });

        sete_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sete_btn.setText("7");
        sete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sete_btnActionPerformed(evt);
            }
        });

        oito_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oito_btn.setText("8");
        oito_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oito_btnActionPerformed(evt);
            }
        });

        nove_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nove_btn.setText("9");
        nove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nove_btnActionPerformed(evt);
            }
        });

        seis_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seis_btn.setText("6");
        seis_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_btnActionPerformed(evt);
            }
        });

        cinco_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cinco_btn.setText("5");
        cinco_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinco_btnActionPerformed(evt);
            }
        });

        dois_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dois_btn.setText("2");
        dois_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dois_btnActionPerformed(evt);
            }
        });

        tres_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tres_btn.setText("3");
        tres_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres_btnActionPerformed(evt);
            }
        });

        ce_btn.setBackground(new java.awt.Color(106, 52, 52));
        ce_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ce_btn.setText("CE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(zero_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ponto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(igual_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sete_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oito_btn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(um_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dois_btn))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(quatro_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_btn)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ce_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tres_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seis_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nove_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(menos_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mult_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mais_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(v_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(div_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c_btn, ce_btn, cinco_btn, div_btn, dois_btn, mais_btn, menos_btn, mult_btn, nove_btn, oito_btn, ponto_btn, quatro_btn, seis_btn, sete_btn, tres_btn, um_btn, v_btn, zero_btn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visor, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_btn)
                    .addComponent(ce_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div_btn)
                    .addComponent(v_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nove_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seis_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tres_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sete_btn)
                            .addComponent(oito_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quatro_btn)
                            .addComponent(cinco_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(um_btn)
                            .addComponent(dois_btn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mult_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menos_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mais_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(igual_btn)
                    .addComponent(ponto_btn)
                    .addComponent(zero_btn))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {c_btn, ce_btn, cinco_btn, div_btn, dois_btn, mais_btn, menos_btn, mult_btn, nove_btn, oito_btn, ponto_btn, quatro_btn, seis_btn, sete_btn, tres_btn, um_btn, v_btn, zero_btn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zero_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+0);
    }//GEN-LAST:event_zero_btnActionPerformed

    private void um_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_um_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+1);
    }//GEN-LAST:event_um_btnActionPerformed

    private void dois_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dois_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+2);
    }//GEN-LAST:event_dois_btnActionPerformed

    private void tres_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+3);
    }//GEN-LAST:event_tres_btnActionPerformed

    private void quatro_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatro_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+4);
    }//GEN-LAST:event_quatro_btnActionPerformed

    private void cinco_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinco_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+5);
    }//GEN-LAST:event_cinco_btnActionPerformed

    private void seis_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+6);
    }//GEN-LAST:event_seis_btnActionPerformed

    private void sete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sete_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+7);
    }//GEN-LAST:event_sete_btnActionPerformed

    private void oito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oito_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+8);
    }//GEN-LAST:event_oito_btnActionPerformed

    private void nove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nove_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+9);
    }//GEN-LAST:event_nove_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_btn;
    private javax.swing.JButton ce_btn;
    private javax.swing.JButton cinco_btn;
    private javax.swing.JButton div_btn;
    private javax.swing.JButton dois_btn;
    private javax.swing.JButton igual_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mais_btn;
    private javax.swing.JButton menos_btn;
    private javax.swing.JButton mult_btn;
    private javax.swing.JButton nove_btn;
    private javax.swing.JButton oito_btn;
    private javax.swing.JButton ponto_btn;
    private javax.swing.JButton quatro_btn;
    private javax.swing.JButton seis_btn;
    private javax.swing.JButton sete_btn;
    private javax.swing.JButton tres_btn;
    private javax.swing.JButton um_btn;
    private javax.swing.JButton v_btn;
    private javax.swing.JTextField visor;
    private javax.swing.JButton zero_btn;
    // End of variables declaration//GEN-END:variables
}
