/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Calculadora extends javax.swing.JFrame {
    double valor1=0,valor2=0, resultado=0;
    int operacao=0;
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        URL url = this.getClass().getClassLoader().getResource("com/imagens/Calculator_30001.png"); 
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        visor = new javax.swing.JTextField();
        c_btn = new javax.swing.JButton();
        v_btn = new javax.swing.JButton();
        div_btn = new javax.swing.JButton();
        mult_btn = new javax.swing.JButton();
        menos_btn = new javax.swing.JButton();
        mais_btn = new javax.swing.JButton();
        igual_btn = new javax.swing.JButton();
        ponto_btn = new javax.swing.JButton();
        zero_btn = new javax.swing.JButton();
        um_btn = new javax.swing.JButton();
        quatro_btn = new javax.swing.JButton();
        sete_btn = new javax.swing.JButton();
        oito_btn = new javax.swing.JButton();
        nove_btn = new javax.swing.JButton();
        seis_btn = new javax.swing.JButton();
        cinco_btn = new javax.swing.JButton();
        dois_btn = new javax.swing.JButton();
        tres_btn = new javax.swing.JButton();
        ce_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaptionBorder);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        visor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        visor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        visor.setBorder(null);
        visor.setOpaque(false);
        visor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                visorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                visorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                visorKeyTyped(evt);
            }
        });

        c_btn.setBackground(new java.awt.Color(106, 52, 52));
        c_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c_btn.setText("C");
        c_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_btnActionPerformed(evt);
            }
        });

        v_btn.setBackground(new java.awt.Color(106, 52, 52));
        v_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        v_btn.setText("<");
        v_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_btnActionPerformed(evt);
            }
        });

        div_btn.setBackground(new java.awt.Color(126, 134, 145));
        div_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        div_btn.setText("/");
        div_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div_btnActionPerformed(evt);
            }
        });

        mult_btn.setBackground(new java.awt.Color(126, 134, 145));
        mult_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mult_btn.setText("X");
        mult_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mult_btnActionPerformed(evt);
            }
        });

        menos_btn.setBackground(new java.awt.Color(126, 134, 145));
        menos_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menos_btn.setText("-");
        menos_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_btnActionPerformed(evt);
            }
        });

        mais_btn.setBackground(new java.awt.Color(126, 134, 145));
        mais_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mais_btn.setText("+");
        mais_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mais_btnActionPerformed(evt);
            }
        });

        igual_btn.setBackground(java.awt.SystemColor.activeCaption);
        igual_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        igual_btn.setText("=");
        igual_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igual_btnActionPerformed(evt);
            }
        });

        ponto_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ponto_btn.setText(".");
        ponto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponto_btnActionPerformed(evt);
            }
        });

        zero_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zero_btn.setText("0");
        zero_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_btnActionPerformed(evt);
            }
        });

        um_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        um_btn.setText("1");
        um_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                um_btnActionPerformed(evt);
            }
        });

        quatro_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quatro_btn.setText("4");
        quatro_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatro_btnActionPerformed(evt);
            }
        });

        sete_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sete_btn.setText("7");
        sete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sete_btnActionPerformed(evt);
            }
        });

        oito_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oito_btn.setText("8");
        oito_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oito_btnActionPerformed(evt);
            }
        });

        nove_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nove_btn.setText("9");
        nove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nove_btnActionPerformed(evt);
            }
        });

        seis_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seis_btn.setText("6");
        seis_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_btnActionPerformed(evt);
            }
        });

        cinco_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cinco_btn.setText("5");
        cinco_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinco_btnActionPerformed(evt);
            }
        });

        dois_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dois_btn.setText("2");
        dois_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dois_btnActionPerformed(evt);
            }
        });

        tres_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tres_btn.setText("3");
        tres_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres_btnActionPerformed(evt);
            }
        });

        ce_btn.setBackground(new java.awt.Color(106, 52, 52));
        ce_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ce_btn.setText("CE");
        ce_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ce_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(zero_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ponto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(igual_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sete_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oito_btn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(um_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dois_btn))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(quatro_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_btn)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ce_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tres_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seis_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nove_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(menos_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mult_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mais_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(v_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(div_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c_btn, ce_btn, cinco_btn, div_btn, dois_btn, mais_btn, menos_btn, mult_btn, nove_btn, oito_btn, ponto_btn, quatro_btn, seis_btn, sete_btn, tres_btn, um_btn, v_btn, zero_btn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_btn)
                    .addComponent(ce_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div_btn)
                    .addComponent(v_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nove_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seis_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tres_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sete_btn)
                            .addComponent(oito_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quatro_btn)
                            .addComponent(cinco_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(um_btn)
                            .addComponent(dois_btn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mult_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menos_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mais_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(igual_btn)
                    .addComponent(ponto_btn)
                    .addComponent(zero_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {c_btn, ce_btn, cinco_btn, div_btn, dois_btn, mais_btn, menos_btn, mult_btn, nove_btn, oito_btn, ponto_btn, quatro_btn, seis_btn, sete_btn, tres_btn, um_btn, v_btn, zero_btn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zero_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+0);
        
        visor.requestFocus();
    }//GEN-LAST:event_zero_btnActionPerformed

    private void um_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_um_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+1);
        
        visor.requestFocus();
    }//GEN-LAST:event_um_btnActionPerformed

    private void dois_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dois_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+2);
        
        visor.requestFocus();
    }//GEN-LAST:event_dois_btnActionPerformed

    private void tres_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+3);
        
        visor.requestFocus();
    }//GEN-LAST:event_tres_btnActionPerformed

    private void quatro_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatro_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+4);
        
        visor.requestFocus();
    }//GEN-LAST:event_quatro_btnActionPerformed

    private void cinco_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinco_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+5);
        
        visor.requestFocus();
    }//GEN-LAST:event_cinco_btnActionPerformed

    private void seis_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+6);
        
        visor.requestFocus();
    }//GEN-LAST:event_seis_btnActionPerformed

    private void sete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sete_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+7);
        
        visor.requestFocus();
    }//GEN-LAST:event_sete_btnActionPerformed

    private void oito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oito_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+8);
        
        visor.requestFocus();
    }//GEN-LAST:event_oito_btnActionPerformed

    private void nove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nove_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+9);
        
        visor.requestFocus();
    }//GEN-LAST:event_nove_btnActionPerformed

    private void c_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_btnActionPerformed
        // TODO add your handling code here:
        visor.setText("");
        valor1=0;
        valor2=0;
        resultado=0;
        
        visor.requestFocus();
    }//GEN-LAST:event_c_btnActionPerformed

    private void ce_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ce_btnActionPerformed
        // TODO add your handling code here:
        visor.setText("");
        
        visor.requestFocus();
    }//GEN-LAST:event_ce_btnActionPerformed

    private void v_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_btnActionPerformed
        // TODO add your handling code here:
        String s = visor.getText();
        if (s.length() > 0) {
            s = s.substring (0, s.length() - 1);
        }
        visor.setText(s);
        
        visor.requestFocus();
    }//GEN-LAST:event_v_btnActionPerformed

    private void igual_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igual_btnActionPerformed
        // TODO add your handling code here:
        if (valor1 == 0){
            visor.setText(visor.getText());
        }else{
        valor2 = Double.parseDouble(visor.getText());
        
        switch(operacao){
            case 0:
                resultado = valor1 + valor2;
            break;
            case 1:
                resultado = valor1 - valor2;            
            break;
            case 2:
                resultado = valor1 * valor2;            
            break;
            case 3:
                resultado = valor1 / valor2;            
            break;
            default:
                JOptionPane.showMessageDialog(null, "Operação invalida!!!");
            break;
        }
        
        valor1 = resultado;
        visor.setText(String.valueOf(resultado));
        }
        
        visor.requestFocus();
    }//GEN-LAST:event_igual_btnActionPerformed

    private void mais_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mais_btnActionPerformed
        // TODO add your handling code here:
        if(visor.getText().isEmpty() || visor.getText()=="0"){
            JOptionPane.showMessageDialog(null, "Digite um valor!");
        }else{
        valor1 = Double.parseDouble(visor.getText());
        operacao = 0;
        visor.setText("");
        }
        
        visor.requestFocus();
    }//GEN-LAST:event_mais_btnActionPerformed

    private void menos_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_btnActionPerformed
        // TODO add your handling code here:
        if(visor.getText().isEmpty() || visor.getText()=="0"){
            JOptionPane.showMessageDialog(null, "Digite um valor!");
        }else{
        valor1 = Double.parseDouble(visor.getText());
        operacao = 1;
        visor.setText("");}
        
        visor.requestFocus();
    }//GEN-LAST:event_menos_btnActionPerformed

    private void mult_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mult_btnActionPerformed
        // TODO add your handling code here:
        if(visor.getText().isEmpty() || visor.getText()=="0"){
            JOptionPane.showMessageDialog(null, "Digite um valor!");
        }else{
        valor1 = Double.parseDouble(visor.getText());
        operacao = 2;
        visor.setText("");}
        
        visor.requestFocus();
    }//GEN-LAST:event_mult_btnActionPerformed

    private void div_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_btnActionPerformed
        // TODO add your handling code here:
        if(visor.getText().isEmpty() || visor.getText()=="0"){
            JOptionPane.showMessageDialog(null, "Digite um valor!");
        }else{
        valor1 = Double.parseDouble(visor.getText());
        operacao = 3;
        visor.setText("");}
        
        visor.requestFocus();
    }//GEN-LAST:event_div_btnActionPerformed

    private void ponto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponto_btnActionPerformed
        // TODO add your handling code here:
        visor.setText(visor.getText()+".");
        
        visor.requestFocus();
    }//GEN-LAST:event_ponto_btnActionPerformed

    private void visorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visorKeyReleased
        
    }//GEN-LAST:event_visorKeyReleased

    private void visorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visorKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            v_btn.doClick();
        }
    }//GEN-LAST:event_visorKeyTyped

    private void visorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visorKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ADD){
            mais_btn.doClick();
        }
         if(evt.getKeyCode() == KeyEvent.VK_SUBTRACT){
            menos_btn.doClick();
        }
         if(evt.getKeyCode() == KeyEvent.VK_MULTIPLY){
            mult_btn.doClick();
        }
         if(evt.getKeyCode() == KeyEvent.VK_DIVIDE){
            div_btn.doClick();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            c_btn.doClick();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            igual_btn.doClick();
        }        
    }//GEN-LAST:event_visorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_btn;
    private javax.swing.JButton ce_btn;
    private javax.swing.JButton cinco_btn;
    private javax.swing.JButton div_btn;
    private javax.swing.JButton dois_btn;
    private javax.swing.JButton igual_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mais_btn;
    private javax.swing.JButton menos_btn;
    private javax.swing.JButton mult_btn;
    private javax.swing.JButton nove_btn;
    private javax.swing.JButton oito_btn;
    private javax.swing.JButton ponto_btn;
    private javax.swing.JButton quatro_btn;
    private javax.swing.JButton seis_btn;
    private javax.swing.JButton sete_btn;
    private javax.swing.JButton tres_btn;
    private javax.swing.JButton um_btn;
    private javax.swing.JButton v_btn;
    private javax.swing.JTextField visor;
    private javax.swing.JButton zero_btn;
    // End of variables declaration//GEN-END:variables
}
